include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unused_import: ignore
    deprecated_member_use: ignore
    unnecessary_null_comparison: ignore
    unnecessary_non_null_assertion: ignore
    unused_field: ignore
    dead_null_aware_expression: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
